# Generated by Django 5.1 on 2024-10-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
