# Generated by Django 5.1 on 2024-10-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_model_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='brand',
        ),
    ]
