# Generated by Django 5.1 on 2024-10-13 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_rename_name_brand_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='name',
            new_name='model',
        ),
    ]
