# Generated by Django 5.1 on 2024-10-13 19:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_rename_name_model_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car/media/uploads/')),
                ('name', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('quantity', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.model')),
            ],
        ),
    ]
