# Generated by Django 5.1 on 2024-10-13 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
