# Generated by Django 5.1 on 2024-10-14 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_alter_comment_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='model',
        ),
    ]
